name: Build & Push Docker Image
run-name: ðŸ³ Build & Push Docker Image
on:
  push:
    branches: 
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:

      - name: Install Jq
        run: sudo apt-get install jq -y  

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Calculate new Docker tag
        id: calculate_tag
        run: |
          LAST_TAG=$(curl -s https://hub.docker.com/v2/repositories/${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}/tags/?page_size=5 | jq -r '.results[0].name' || echo "0.0")
          echo "Last tag: $LAST_TAG"
          MAJOR=$(echo "$LAST_TAG" | cut -d'.' -f1)
          NEW_MAJOR=$((MAJOR + 1))
          NEW_TAG="${NEW_MAJOR}.0"
          echo "Calculated new tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.calculate_tag.outputs.NEW_TAG }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:lts

      - name: Test Docker image
        run: |
          docker run -d -p 3000:3000 ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.calculate_tag.outputs.NEW_TAG }}
          sleep 15
          curl -f http://localhost:3000 || { echo "The application didn't respond on port 3000"; exit 1; }
          echo "The application responds correctly on port 3000."

      - name: Push Docker image
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.calculate_tag.outputs.NEW_TAG }}
            ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:lts